---
  - name: Move CSV files older than 1 day to archives directory
    find:
      paths: "{{ reportdir }}"
      patterns: "*.csv*"
      age: 1d
      file_type: file
    register: csv_files_to_move

  - name: Move CSV files to archives directory
    file:
      src: "{{ item.path }}"
      dest: "{{ archivedir }}"
      state: hard
    with_items: "{{ csv_files_to_move.files }}"

  - name: Remove the CSV files older than 1 day 
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ csv_files_to_move.files }}"  
