---
  - name: Move CSV files older than 1 day to archives directory
    find:
      paths: /SP_CONTAINER_REPORTS
      patterns: "*.csv*"
      age: 1d
      file_type: file
    register: csv_files_to_move

  - name: Move CSV files to archives directory
    file:
      src: "{{ item.path }}"
      dest: "{{ archivedir }}"
    with_items: "{{ csv_files_to_move.files }}"
