---
    - name: " Remove Temp file beining of Play"
      file:
        path: "{{ tempcontainer }}"
        state: absent
    - name: " To Create File with current date "
      lineinfile:
        path: "/SP_CONTAINER_REPORTS/Container_Space_savings_Percentage_{{ date }}.csv"
        line: "NAME,SPACE_SAVED_PCT,SPACE_SAVED_MB,USED_SPACE,DEDUP_SAVED_MB,DEDUP_SAVED_PCT,COMP_SAVED_MB,COMP_SAVED_PCT"
        create: true  
    - name: "To get Container Storage pool space savings With Percentage"
      dsmadmc:
        command: " select name, SPACE_SAVED_PCT, SPACE_SAVED_MB, USED_SPACE, DEDUP_SAVED_MB, DEDUP_SAVED_PCT, COMP_SAVED_MB, COMP_SAVED_PCT from TSMGUI_ALLSTG_GRID where STG_TYPE=101 or STG_TYPE=100 order by SPACE_SAVED_PCT DESC > {{ tempcontainer }}"
        se: "{{ lookup('env', 'tsm_server_node') }}"
        id: "{{ lookup('env', 'tsm_app_user') }}"
        pa: "{{ lookup('env', 'tsm_app_password') }}"
        dataonly: true
        comma: true
      register: output
    - debug: 
        msg: "{{output.stdout_lines}}"
    - name: Read data from Tempfile
      slurp:
        src: "{{ tempcontainer }}"
      register: file1_data
    - name: Append data to Final file
      lineinfile:
        path: /SP_CONTAINER_REPORTS/Container_Space_savings_Percentage_{{ date }}.csv
        line: "{{ item }}"
        create: yes
      with_items: "{{ file1_data['content'] | b64decode }}"                                   
    - name: " Remove Temp file at end of Play"
      file:
        path: "{{ tempcontainer }}"
        state: absent