---
    - shell: " rm -rf /tmp/dailyingest.csv "
    - shell: " echo DATE,PROTECTED_GB,WRITTEN_GB,DEDUPSAVINGS_GB,COMPSAVINGS_GB,DEDUP_PCT,COMP_PCT > /tmp/Dailyingest_$(date +'%Y-%m-%d').csv"  
    - name: "To get Container Storage pool space savings"
      dsmadmc:
        command: "SELECT DATE(s.START_TIME) AS Date, (CAST(FLOAT(SUM(s.bytes_protected))/1024/1024/1024 AS DECIMAL(12,2))) AS PROTECTED_GB, (CAST(FLOAT(SUM(s.bytes_written))/1024/1024/1024 AS DECIMAL(12,2))) AS WRITTEN_GB, (CAST(FLOAT(SUM(s.dedup_savings))/1024/1024/1024 AS DECIMAL(12,2))) AS DEDUPSAVINGS_GB, (CAST(FLOAT(SUM(s.comp_savings))/1024/1024/1024 AS DECIMAL(12,2))) AS COMPSAVINGS_GB, (CAST(FLOAT(SUM(s.dedup_savings))/FLOAT(SUM(s.bytes_protected))*100 AS DECIMAL(5,2))) AS DEDUP_PCT, (CAST(FLOAT(SUM(s.comp_savings))/FLOAT(SUM(s.bytes_protected)-SUM(s.dedup_savings))*100 AS DECIMAL(5,2))) AS COMP_PCT from summary s WHERE activity='BACKUP' or activity='ARCHIVE' GROUP BY DATE(S.START_TIME) ORDER BY DATE DESC > /tmp/dailyingest.csv"
        se: "{{ lookup('csvfile', 'Server file=credentials.csv delimiter=,') }}"
        id: "{{ lookup('csvfile', 'ID file=credentials.csv delimiter=,') }}"
        pa: "{{ lookup('csvfile', 'Password file=credentials.csv delimiter=,') }}"
        dataonly: true
        comma: true
      register: output
    - debug: 
        msg: "{{output.stdout_lines}}"
    - shell: " cat /tmp/dailyingest.csv >> /tmp/Dailyingest_$(date +'%Y-%m-%d').csv "
    - shell: " rm -rf /tmp/dailyingest.csv "