---
    - name: " Remove Temp file at end of Play"
      file:
        path: "{{ tempcontainer }}"
        state: absent    
    - name: " To Create File with current date "
      lineinfile:
        path: "{{ reportdir }}/dailyingest_{{ date }}.csv"
        line: "DATE,PROTECTED_GB,WRITTEN_GB,DEDUPSAVINGS_GB,COMPSAVINGS_GB,DEDUP_PCT,COMP_PCT"
        create: true                 
    - name: "To get Container Storage pool space savings"
      dsmadmc:
        command: "SELECT DATE(s.START_TIME) AS Date, (CAST(FLOAT(SUM(s.bytes_protected))/1024/1024/1024 AS DECIMAL(12,2))) AS PROTECTED_GB, (CAST(FLOAT(SUM(s.bytes_written))/1024/1024/1024 AS DECIMAL(12,2))) AS WRITTEN_GB, (CAST(FLOAT(SUM(s.dedup_savings))/1024/1024/1024 AS DECIMAL(12,2))) AS DEDUPSAVINGS_GB, (CAST(FLOAT(SUM(s.comp_savings))/1024/1024/1024 AS DECIMAL(12,2))) AS COMPSAVINGS_GB, (CAST(FLOAT(SUM(s.dedup_savings))/FLOAT(SUM(s.bytes_protected))*100 AS DECIMAL(5,2))) AS DEDUP_PCT, (CAST(FLOAT(SUM(s.comp_savings))/FLOAT(SUM(s.bytes_protected)-SUM(s.dedup_savings))*100 AS DECIMAL(5,2))) AS COMP_PCT from summary s WHERE activity='BACKUP' or activity='ARCHIVE' GROUP BY DATE(S.START_TIME) ORDER BY DATE DESC > {{ tempcontainer }}"
        se: "{{ lookup('env', 'tsm_server_node') }}"
        id: "{{ lookup('env', 'tsm_app_user') }}"
        pa: "{{ lookup('env', 'tsm_app_password') }}"
        dataonly: true
        comma: true
      register: output
    - debug: 
        msg: "{{output.stdout_lines}}"
    - name: Read data from Tempfile
      slurp:
        src: "{{ tempcontainer }}"
      register: file1_data
    - name: Append data to Final file
      lineinfile:
        path: "{{ reportdir }}/dailyingest_{{ date }}.csv"
        line: "{{ item }}"
        create: yes
      with_items: "{{ file1_data['content'] | b64decode }}"           
    - name: " Remove Temp file at end of Play"
      file:
        path: "{{ tempcontainer }}"
        state: absent        