---
    - include_tasks: tasks/removetemp.yml    
    - name: " To Create File with current date "
      lineinfile:
        path: "{{ reportdir }}/Node_Container_Backups__{{ date }}.csv"
        line: "NODE_NAME,START_TIME,PROTECTED_MB,WRITTEN_MB,DEDUPSAVINGS_MB,COMPSAVINGS_MB,DEDUP_PCT"
        create: true      
    - name: "To get Container Node Bakcups 24hours status"
      dsmadmc:
        command: "SELECT ENTITY as NODE_NAME, s.START_TIME, (CAST(FLOAT((s.bytes_protected))/1024/1024 AS DECIMAL(12,2))) AS PROTECTED_MB, (CAST(FLOAT((s.bytes_written))/1024/1024 AS DECIMAL(12,2))) AS WRITTEN_MB, (CAST(FLOAT((s.dedup_savings))/1024/1024 AS DECIMAL(12,2))) AS DEDUPSAVINGS_MB, (CAST(FLOAT((s.comp_savings))/1024/1024 AS DECIMAL(12,2))) AS COMPSAVINGS_MB, (CAST(FLOAT((s.dedup_savings))/FLOAT((s.bytes_protected))*100 AS DECIMAL(5,2))) AS DEDUP_PCT from summary s WHERE s.bytes_protected<>0 and (activity='BACKUP' or activity='ARCHIVE') and s.START_TIME>=(current_date - 1 days) order by s.start_time > {{ tempcontainer }}"
        se: "{{ lookup('env', 'tsm_server_node') }}"
        id: "{{ lookup('env', 'tsm_app_user') }}"
        pa: "{{ lookup('env', 'tsm_app_password') }}"
        dataonly: true
        comma: true
      register: output
    - debug: 
        msg: "{{output.stdout_lines}}"
    - include_tasks: tasks/readtempfile.yml
    - name: Append data to Final file
      lineinfile:
        path: "{{ reportdir }}/Node_Container_Backups__{{ date }}.csv"
        line: "{{ item }}"
        create: yes
      with_items: "{{ file1_data['content'] | b64decode }}"                   
    - include_tasks: tasks/removetemp.yml     